Redesigned Club Q page
GRI-ESPCI/pc-est-magique pull request #21
Opened 2023-09-09 05:05 UTC by caalec

2023-09-10 15:07 UTC, loic-simon requested changes

2023-09-10 15:07 UTC, loic-simon commented on .gitignore
> +to do
comment ça mon reuf

2023-09-10 15:07 UTC, loic-simon commented on README.md
> +  nano logs/mails.log
Si c'est jutste pour créer un fichier vide, tu peux utiliser `touch` plutôt que `nano` :grin:

(mais si je capte bien ce que tu veux résoudre, juste créer le dossier suffit, le fichier il sait le créer)

2023-09-10 15:07 UTC, loic-simon commented on app/email.py
> +
Si jamais je passe `sender="choucroute"`, il se passe quoi ? Ça plante ? :grin:

J'aurais tendance à mettre en argument `sender: str = "ADMINS"`, et 
```py
    sender_mail = flask.current_app.config[sender][0]
```

Et tu passes `sender="CLUB_Q"` quand tu en as besoin, comme ça si tu passes n'importe quoi ça fail de manière plus claire. Ou a minima, si tu veux garder ce fonctionnement, 

```py
    if sender == "club_q":
        sender_mail = flask.current_app.config["CLUB_Q"][0]
    else:
        sender_mail = flask.current_app.config["ADMINS"][0]
```

2023-09-10 15:07 UTC, loic-simon commented on app/models/auth.py
> +            )
Là tu construit ta query sans l'exécuter, donc tu n'auras jamais `None` ? Tu veux ajouter un `.one_or_none()` je pense

```suggestion
            self.clubq_voeux.filter_by(
                _season_id=models.GlobalSetting.query.filter_by(key="SEASON_NUMBER_CLUB_Q").one().value
            ).one_or_none()
```

Par ailleurs, j'aurais tendance à récupérer la `season_id` dans une ligne à part au dessus du `if`, ce sera vachement plus lisible 😉

2023-09-10 15:07 UTC, loic-simon commented on app/models/club_q.py
> +        return sum(spect.sum_places_attribuees for spect in ClubQSpectacle.query.filter_by(_season_id=self.id))
Pourquoi ne pas utiliser la relation directement ?

```suggestion
        return sum(spect.sum_places_demandees for spect in self.spectacles)

    @property
    def sum_places_attribuees(self) -> int:
        """The sum of all the places asked in a season"""
        return sum(spect.sum_places_attribuees for spect in self.spectacles)
```

2023-09-10 15:07 UTC, loic-simon commented on app/models/club_q.py
> +    longitude: Column[float | 0] = column(sa.Float(), nullable=True)
Heu, `float | 0` c'est tout à fait illégal comme syntaxe

![image](https://github.com/GRI-ESPCI/pc-est-magique/assets/62268282/c3669327-6096-4281-9a02-4ffb1fa95843)

À la limite tu pourrais vouloir dire `float | Literal[0]`, mais 
  1. 0 est déjà inclus dans float, donc ça sert pas à grand choes
  2. Si tu laisses la colonne nullable, c'est juste faux ?

2023-09-10 15:07 UTC, loic-simon commented on app/routes/club_q/algorithm.py
> +            if corruption and random.random() > 0.99:
mdrr quelle ligne de fou

2023-09-10 15:07 UTC, loic-simon commented on app/routes/club_q/algorithm.py
> +                club_q_algo_logger.info(efioohze[i])
Par contre c'est quoi ces noms de variable

2023-09-10 15:07 UTC, loic-simon commented on app/routes/club_q/routes.py
> +# @context.permission_condition(lambda: bool(GlobalSetting.query.filter_by(key='ACCESS_CLUB_Q').one().value))
Normal ce commentaire ?

2023-09-10 15:07 UTC, loic-simon commented on app/routes/club_q/routes.py
> +        spect.date = spect.date.strftime("%d %B %Y, %H:%M:%S")
Là tu vas modifier la date du spectacle dans l'objet, c'est vraiment ce que tu veux ?

2023-09-10 15:07 UTC, loic-simon commented on app/routes/club_q/routes.py
> +                    flask.flash(_("Un voeu a été défini avec une priorité mais sans un nombre de places."))
Tu devrais préciser la category "warning", sinon tout ça va être flash en "info"

2023-09-10 15:07 UTC, loic-simon commented on app/routes/club_q/utils.py
> +    return len(query)
Tu peux faire un `.count` plutôt que `len(.all)` :wink:

2023-09-10 15:07 UTC, loic-simon commented on app/templates/club_q/common.html
> +<style>
Hmm, tu voudrais pas mettre ça dans un fichier CSS quand même ? :grin:

2023-09-10 15:07 UTC, loic-simon commented on app/templates/club_q/id/salle.html
> +></iframe>
stylé

2023-09-10 15:07 UTC, loic-simon commented on app/models/club_q.py
> +    fin_inscription: Column[datetime.date | None] = column(sa.Date(), nullable=True)
Je vois pas de migration pour ce changement ? C'est pas dramaitque, parce que date et datetime sont relativement compatibles, mais ce serait mieux quand même

2023-09-10 15:07 UTC, loic-simon commented on CHANGELOG.md
> +- Club Q Booking page now takes in account was wishes were made before
Il me semble que tu as oublié le changement correspondant dans `changelog.html`

Bon ça ne sert pas à grand chose, masi quand même

2023-09-10 16:08 UTC, caalec commented on CHANGELOG.md
> +- Club Q Booking page now takes in account was wishes were made before
Les petttes choses ont leur importance ! Je corrige ça

2023-09-10 16:15 UTC, caalec commented on .gitignore
> +to do
Un fichier qui traînait pour le suivi de l'avancement et une fausse manip plus tard, je pense que ça peut expliquer

2023-09-10 16:16 UTC, caalec commented on app/templates/club_q/id/salle.html
> +></iframe>
(à moitié fonctionnel, des fois l'image se centrera sur 4x la carte du monde. Il y a des modules pour faire ça plus proprement mais j'ai eu la flemme)

2023-09-10 16:17 UTC, caalec commented on app/templates/club_q/common.html
> +<style>
ça peut se faire!

2023-09-10 16:22 UTC, caalec commented on app/models/auth.py
> +            )
Je suis presque sûr que je n'utilise plus cette propriété donc ça va partir sur une suppression. (Le problème étant que je ne peux pas envoyer une variable saison en même temps, et en plus je peux utiliser .exist() pour les query)

2023-09-10 16:24 UTC, caalec commented on app/models/club_q.py
> +    fin_inscription: Column[datetime.date | None] = column(sa.Date(), nullable=True)
Ah oui, parce que je l'ai fait depuis la db - je vais faire ça proprement

2023-09-10 16:25 UTC, caalec commented on app/models/club_q.py
> +        return sum(spect.sum_places_attribuees for spect in ClubQSpectacle.query.filter_by(_season_id=self.id))
C'est effectivement une riche idée

2023-09-10 16:36 UTC, caalec commented on app/routes/club_q/algorithm.py
> +                club_q_algo_logger.info(efioohze[i])
un nom aléatoire

2023-09-10 16:38 UTC, caalec commented on app/routes/club_q/routes.py
> +# @context.permission_condition(lambda: bool(GlobalSetting.query.filter_by(key='ACCESS_CLUB_Q').one().value))
Ancienne manière de réguler l'accès à la page de réservation, du coup plus nécessaire, je supprime ça

2023-09-10 16:40 UTC, caalec commented on app/routes/club_q/routes.py
> +        spect.date = spect.date.strftime("%d %B %Y, %H:%M:%S")
C'est la problématique des fuseaux horaires, il me semble que j'utilisais avant un fuseau horaire et c'était assez compliqué - du coup cette ligne me permet de convertir en temps que date/heure sans fuseau horaire intégré (si je ne dis pas de bétîse). à la longue normalement ça ne devrait plus être nécessaire

2023-09-10 17:35 UTC, loic-simon commented on app/templates/club_q/id/salle.html
> +></iframe>
c'est pas quand ta lat/lon est pas définie ça ?

2023-09-10 17:36 UTC, loic-simon commented on app/routes/club_q/routes.py
> +        spect.date = spect.date.strftime("%d %B %Y, %H:%M:%S")
Heu normalement l'heure est stockée en UTC en base, et `strftime` ne fait rien à ce niveau ?

2023-09-16 16:57 UTC, loic-simon commented
All good!

2023-09-16 17:05 UTC, merged