Bekk module
GRI-ESPCI/pc-est-magique pull request #23
Opened 2023-09-27 07:10 UTC by caalec

2023-09-27 07:58 UTC, caalec commented on app/static/js/jquery.js
Question à ce niveau là : quelle est la meilleure approche ? Soit mettre le fichier en local (même s'il pèse un peu lourd) ou l'utiliser à distance via https://code.jquery.com/jquery-3.7.1.min.js ? Mais j'imagine qu'il existe un risque (même minime) de sécurité si quelqu'un vient à modifier ce lien ?

2023-09-27 09:06 UTC, Itrimel commented on app/static/js/jquery.js
Si ça te pose pb, il doit y avoir moyen d'utiliser l'attribut ìntegrity` sur l'import HTML, ça fait un checksum sur le fichier importé pour garantir que c'est bien celui que tu veux.
J'ai découvert ça dans la doc de cette librairie : https://katex.org/docs/browser

2023-09-27 20:05 UTC, loic-simon requested changes

2023-09-27 20:05 UTC, loic-simon commented on .conf_models/nginx.conf
> +    }
Pas besoin de sécuriser l'accès aux bekks (comme les photos ?) C'est considéré dans le domaine public ?

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +import fitz
kesako ? Je le trouve pas sur pypi, et il est pas dans les requirements.txt ⚠️

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +# @context.permission_only(PermissionType.read, PermissionScope.bekk)
normal ?

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +    promos.sort(reverse=True)
Laisse moi t'introduire au monde merveilleux des set comprehensions : 

```suggestion
    promos = sorted({bekk.promo for bekk in bekks}, reverse=True)
```

`{x for x in [1, 2, 2]} == {1, 2}`, et utiliser `reversed` te le convertit en liste + trie en un coup :grin:

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +        promo = GlobalSetting.query.filter_by(key="PROMO_1A").one().value  # ID of the season to show
ptit commentaire oublié ?

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +            promo = promo - 1
Et si `promo - 1 not in promos` ? :grin:

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +    if promo == None:
plutôt utiliser `is` avec None : https://stackoverflow.com/a/14247383

```suggestion
    if promo is None:
```

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +            if form["pdf_file"].data == None:
```suggestion
            if form["pdf_file"].data is None:
```

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +                    os.mkdir(os.path.join(bekk_path, form["promo"].data, form["bekk_name"].data))
Ce serait plus clean avec des variables intermédiaires quand même

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +                    )
pareil, pitié met moi ce path dans une variable 😵‍💫

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +                    )
Heu... pourquoi on a besoin de faire ça exactement ? (j'ai peur)

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +                if not os.path.exists(os.path.join(bekk_path, form["promo"].data, form["bekk_name"].data)):
J'aurais pas tendance à utiliser `bekk_name` dans un path : tu peux avoir des espaces, majuscules, accents... dedans, c'est pas ouf. Franchement je serais toi je m'embêterai pas et je stockerai les bekk par ID, tous dans le même dossier

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +                        if file.split(".")[-1] == "png":
protip : https://docs.python.org/3/library/os.path.html#os.path.splitext

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +                    files = os.listdir(os.path.join(bekk_path, old_promo, old_name))
mon commentaire sur le stockage par ID plut haut ferait que t'as pas à t'embêter avec tout ça 😄

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +    return flask.render_template("bekk/reader.html", title=_(bekk.name), bekk=bekk, pages=pages)
Ça ne sert à rien d'essayer de traduire un nom dynamique (stocké en base) :wink:

```suggestion
    return flask.render_template("bekk/reader.html", title=bekk.name, bekk=bekk, pages=pages)
```

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +# @context.permission_only(PermissionType.read, PermissionScope.bekk)
.

2023-09-27 20:05 UTC, loic-simon commented on app/static/js/bekk/reader.js
> +
Ce code bient d'une lib ou autre ? Si oui c'est cool de mettre un commentaire pour le dire en haut (et si non, GG !)

2023-09-27 20:05 UTC, loic-simon commented on app/static/js/jquery.js
ça me pose un peu pb d'utiliser jQuery de base, je préférais rester en pure JS... mais si ta lib en a besoin, on peut toujours fait avec.

Pour ta question, on peut pas ship ta library (turn ?) avec `bower`, comme la plupart de nos autres libs JS ? Voir par exemple ce que j'ai fait pour `lightgallery` dans https://github.com/GRI-ESPCI/pc-est-magique/blob/main/app/templates/photos/album.html

Dans tous les cas, on a pas très envie de versionner jquery dans notre code non 😄

2023-09-27 20:05 UTC, loic-simon commented on app/routes/bekk/routes.py
> +    if form.validate_on_submit():
Tu vérifies qu'on a le droit `write/bekk` quelque part en back ?

2023-09-27 20:05 UTC, loic-simon commented on app/templates/bekk/main.html
> +    Le Bekk est l'association journalistique de l'école, et produit plusieurs numéros par an, à des occasions et des
plutôt séparer ça en deux traductions quand même, on évite trop d'HTML quand on peut

```suggestion
    {{ _("Bienvenue sur la page du Bekk de l'ESPCI.") }}
    <br />
    {{ _("Le Bekk est l'association journalistique de l'école, et produit plusieurs numéros par an, à des occasions et des
```

2023-09-27 20:05 UTC, loic-simon commented on app/templates/bekk/reader.html
> +></script>
important : utiliser `defer` à la fin de tes tags script pour ne pas ralentir le chargement de la page

Voir https://developer.mozilla.org/fr/docs/Web/HTML/Element/script

2023-09-27 20:05 UTC, loic-simon commented on app/templates/bekk/reader.html
> +    ></div>
attend on affiche les bekk en images et pas en PDF là ??? mais enfin pourquoi s'infliger ça ?

2023-09-27 20:05 UTC, loic-simon commented on app/templates/bekk/reader.html
> +  ></script>
pourquoi le mettre en bas ? Est-ce qu'utiliser `defer` répond à ton besoin ?

2023-09-27 20:05 UTC, loic-simon commented on scripts/update_roles.py
> +        "access_bekk": dict(type=PermissionType.read, scope=PermissionScope.bekk, ref_id=None),
Heu, je vois pas la modification de l'enum dans les modèles ?

2023-09-27 20:05 UTC, loic-simon commented on README.md
> +- Ajout du module du Bekk sur pc-est-magique : possibilité de le lire en ligne, de le télécharger. Outils d'administration pour l'équipe du Bekk.
Changement correspondant dans `changelog.html` :wink:

2023-09-28 00:10 UTC, caalec commented on .conf_models/nginx.conf
> +    }
Si totalement, je voulais le faire mais j'ai oublié. Je vais corriger ça

2023-09-28 00:12 UTC, caalec commented on app/routes/bekk/routes.py
> +import fitz
C'est PyMuPDF mais pour import c'est fitz

2023-09-28 00:23 UTC, caalec commented on app/routes/bekk/routes.py
> +    if form.validate_on_submit():
Non mais c'est clairement pas une mauvaise idée

2023-09-28 00:26 UTC, caalec commented on app/static/js/bekk/reader.js
> +
On va pas se mentir une partie ça vient de la librairie turn.js et le reste c'est chatgpt qui a fait les excellentes suggestions qu'il a copié quelque part dont j'ignore l'origine

2023-09-28 00:31 UTC, caalec commented on app/templates/bekk/reader.html
> +    ></div>
Parce que j'ai pas réussi à afficher en PDF 😅 - Et après je me suis dit que si j'affichais en tant qu'image ça pourrait marcher mais ça serait gourmand en ressources d'où le fait que j'enregistre les images. Mais comme j'ai fait ça au début quand rien ne marchait je peux retenter d'afficher directement le pdf

2023-09-28 03:24 UTC, caalec commented on scripts/update_roles.py
> +        "access_bekk": dict(type=PermissionType.read, scope=PermissionScope.bekk, ref_id=None),
Tu entends quoi par là ?

2023-09-30 15:51 UTC, loic-simon commented on app/routes/bekk/routes.py
> +import PyPDF2
C'est toujours pas dans `requirements.txt` ça :grin:

2023-09-30 15:51 UTC, loic-simon commented on README.md
> +- Ajout du module du Bekk sur pc-est-magique : possibilité de le lire en ligne, de le télécharger. Outils d'administration pour l'équipe du Bekk.
Sauf erreur il reste ça !

2023-09-30 17:32 UTC, caalec commented on app/routes/bekk/routes.py
> +import PyPDF2
SI je l'ai rajouté pourtant 🤔

2023-09-30 18:23 UTC, loic-simon approved these changes

2023-09-30 18:23 UTC, loic-simon commented on app/routes/bekk/routes.py
> +import PyPDF2
ah oui, je le voyais pas tout à l'heure 😮

2023-09-30 18:28 UTC, merged