Bug fixes - brochures for Club Q
GRI-ESPCI/pc-est-magique pull request #25
Opened 2023-10-02 06:51 UTC by caalec

2023-10-02 19:12 UTC, loic-simon requested changes

2023-10-02 19:12 UTC, loic-simon commented on app/models/club_q.py
> +import flask
qu'est-ce donc que ces imports pas en haut du fichier ?

2023-10-02 19:12 UTC, loic-simon commented on app/routes/club_q/routes.py
> +            wtforms.SelectField(
tiens, tu es obligé de passer par setattr ? Tu peux pas faire `forms.Brochure.season_id = wtforms.SelectField(...` ?

2023-10-02 19:12 UTC, loic-simon commented on app/routes/club_q/routes.py
> +        brochure_id_list.append(brochure.id)
```suggestion
    brochure_id_list = [brochure.id for brochure in brochures]
```

2023-10-02 19:12 UTC, loic-simon commented on app/routes/club_q/routes.py
> +    brochure = ClubQBrochure.query.filter_by(id=id).one_or_none()
tu ne gères pas le cas `None` (ça crash juste en dessous, faudrait renvoyer une 404 plutôt)

2023-10-02 19:12 UTC, loic-simon commented on app/routes/club_q/routes.py
> +    brochure = ClubQBrochure.query.filter_by(id=id).one()
same, le `.one()` va envoyer une 500, 404 serait mieux

2023-10-02 19:12 UTC, loic-simon commented on app/routes/club_q/routes.py
> +@context.permission_only(PermissionType.read, PermissionScope.club_q)
euh, plutôt `write` pour delete non ? :grin:

2023-10-02 19:12 UTC, loic-simon commented on app/routes/main/routes.py
> +    logging.warning("Bekk served by Flask and not nginx!")
du coup pas Bekk :grin:

2023-10-03 00:46 UTC, caalec commented on app/models/club_q.py
> +import flask
L'innovation!

2023-10-03 01:55 UTC, caalec commented on app/routes/club_q/routes.py
> +            wtforms.SelectField(
ça marche même très bien et c'est moins moche

2023-10-03 20:45 UTC, loic-simon approved these changes

2023-10-04 02:04 UTC, merged